-- module Ast2Latex (ast2Latex) where 
-- 
-- import Parser (Node(..), FunctionName(..))
-- 
-- ast2Latex :: [Node] -> String
-- ast2Latex = (fmap node2latex)
-- 
-- node2Latex :: Node -> String
-- node2Latex Atom string = string
-- node2Latex Function funcName args = 
--     case funcName of
--         Author -> author2latex args
-- 
-- author2latex args =
-- 
-- atom2string :: Node
-- 
-- preamble :: String
-- preamble = "\documentclass{article} \usepackage{microtype} \begin{document}"
